spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: category-service
          uri: lb://category
          predicates:
            - Path= /categories/**, /admin/categories/**

        - id: compilation-service
          uri: lb://compilation
          predicates:
            - Path= /admin/compilations/**, /compilations/**

        - id: event-service
          uri: lb://event
          predicates:
            - Path= /events/**, /users/{userId}/events, /users/{userId}/events/{eventsID}, /admin/events,
              /admin/events/{eventId}

        - id: location-service
          uri: lb://location
          predicates:
            - Path= /locations/**, /admin/locations/**

        - id: request-service
          uri: lb://request
          predicates:
            - Path= /users/{userId}/requests/**, /users/{userId}/requests/{requestId}/cancel,
              /users/{userId}/events/{eventId}/requests, requests/events/{eventId}

        - id: user-service
          uri: lb://user
          predicates:
            - Path= /admin/users/**, admin/users/{userId}/**

        - id: stat-service
          uri: lb://stat
          predicates:
            - Path=/hit, /stats/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10