spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: ewm_service_route
          uri: lb://ewm
          predicates:
            - Path=/admin/**, /compilations/**, /categories/**,  /users/**, /events/**, /locations/**
        - id: stats_service_route
          uri: lb://stats
          predicates:
            - Path=/stats/**, /hit/**

server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    preferIpAddress: true
    hostname: localhost
    instance-id: "${spring.application.name}:${random.value}"
    leaseRenewalIntervalInSeconds: 10