spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations:
            - classpath:config/core/{application}
            - classpath:config/{application}
            - classpath:config/infra/{application}
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka