server:
  port: 8080

spring:
  config:
    activate:
      on-profile: test
  h2:
    console:
      enabled: true
  sql:
    init:
      mode: always
  datasource:
    url: jdbc:h2:mem:/ewm
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
stats-server:
  url: http://localhost:9090
  hit: "/hit"
  stats: "/stats"
