server:
  port: 0

spring:
  application:
    name: ewm
  config:
    activate:
      on-profile: dev
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5455/ewm}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true

stats-server:
  url: ${STATS_SERVICE_URL:http://localhost:9090}
  hit: "/hit"
  stats: "/stats"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/