/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
package com.github.artemlv.stats.controller.api;

import dto.EndpointHit;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestBody;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;


@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-08-11T12:04:18.997287900+03:00[Europe/Moscow]", comments = "Generator version: 7.5.0")
@Validated
@Tag(name = "StatsController", description = "API для работы со статистикой посещений")
public interface HitApi {

    /**
     * POST /hit : Сохранение информации о том, что к эндпоинту был запрос
     * Сохранение информации о том, что на uri конкретного сервиса был отправлен запрос пользователем. Название сервиса, uri и ip пользователя указаны в теле запроса.
     *
     * @param endpointHit данные запроса (required)
     * @return Информация сохранена (status code 201)
     */
    @Operation(
        operationId = "hit",
        summary = "Сохранение информации о том, что к эндпоинту был запрос",
        description = "Сохранение информации о том, что на uri конкретного сервиса был отправлен запрос пользователем. Название сервиса, uri и ip пользователя указаны в теле запроса.",
        tags = { "StatsController" },
        responses = {
            @ApiResponse(responseCode = "201", description = "Информация сохранена")
        }
    )
    @RequestMapping(
        method = RequestMethod.POST,
        value = "/hit",
        consumes = "application/json"
    )
    
    ResponseEntity<Void> hit(
        @Parameter(name = "EndpointHit", description = "данные запроса", required = true) @Valid @RequestBody EndpointHit endpointHit
    );

}
