server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5434/${POSTGRES_DB:category-db}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

statsService:
  url:
  name: stats