server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5436/${POSTGRES_DB:event-db}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:password}
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

statsService:
  url:
  name: stats-service
