/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech) (7.5.0).
 * https://openapi-generator.tech Do not edit the class manually.
 */
package client.api;

import dto.ViewStats;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.Parameter;
import io.swagger.v3.oas.annotations.enums.ParameterIn;
import io.swagger.v3.oas.annotations.media.ArraySchema;
import io.swagger.v3.oas.annotations.media.Content;
import io.swagger.v3.oas.annotations.media.Schema;
import io.swagger.v3.oas.annotations.responses.ApiResponse;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.annotation.Generated;
import jakarta.validation.Valid;
import jakarta.validation.constraints.NotNull;
import java.time.LocalDateTime;
import java.util.List;
import org.springframework.http.ResponseEntity;
import org.springframework.validation.annotation.Validated;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.RequestParam;

@Generated(value = "org.openapitools.codegen.languages.SpringCodegen", date = "2024-08-11T12:04:18.997287900+03:00[Europe/Moscow]", comments = "Generator version: 7.5.0")
@Validated
@Tag(name = "StatsController", description = "API для работы со статистикой посещений")
public interface StatsApi {

    /**
     * GET /stats : Получение статистики по посещениям. Обратите внимание: значение даты и времени нужно закодировать (например используя java.net.URLEncoder.encode)
     *
     * @param start Дата и время начала диапазона за который нужно выгрузить статистику (в формате \&quot;yyyy-MM-dd HH:mm:ss\&quot;) (required)
     * @param end Дата и время конца диапазона за который нужно выгрузить статистику (в формате \&quot;yyyy-MM-dd HH:mm:ss\&quot;) (required)
     * @param uris Список uri для которых нужно выгрузить статистику (optional)
     * @param unique Нужно ли учитывать только уникальные посещения (только с уникальным ip) (optional, default to false)
     * @return Статистика собрана (status code 200)
     */
    @Operation(
            operationId = "getStats",
            summary = "Получение статистики по посещениям. Обратите внимание: значение даты и времени нужно закодировать (например используя java.net.URLEncoder.encode)",
            tags = {"StatsController"},
            responses = {
                    @ApiResponse(responseCode = "200", description = "Статистика собрана", content = {
                            @Content(mediaType = "application/json", array = @ArraySchema(schema = @Schema(implementation = ViewStats.class)))
                    })
            }
    )
    @RequestMapping(
            method = RequestMethod.GET,
            value = "/stats",
            produces = {"application/json"}
    )
    ResponseEntity<List<ViewStats>> getStats(
            @NotNull @Parameter(name = "start", description = "Дата и время начала диапазона за который нужно выгрузить статистику (в формате \"yyyy-MM-dd HH:mm:ss\")", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "start", required = true) LocalDateTime start,
            @NotNull @Parameter(name = "end", description = "Дата и время конца диапазона за который нужно выгрузить статистику (в формате \"yyyy-MM-dd HH:mm:ss\")", required = true, in = ParameterIn.QUERY) @Valid @RequestParam(value = "end", required = true) LocalDateTime end,
            @Parameter(name = "uris", description = "Список uri для которых нужно выгрузить статистику", in = ParameterIn.QUERY) @Valid @RequestParam(value = "uris", required = false) List<String> uris,
            @Parameter(name = "unique", description = "Нужно ли учитывать только уникальные посещения (только с уникальным ip)", in = ParameterIn.QUERY) @Valid @RequestParam(value = "unique", required = false, defaultValue = "false") Boolean unique
    );

}
