server:
  port: 0
spring:
  sql:
    init:
      mode: ALWAYS
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5455/ewm}
    username: ${POSTGRES_USER:admin}
    password: ${POSTGRES_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka