server:
  port: 0

spring:
  datasource:
    url: jdbc:postgresql://localhost:5435/${POSTGRES_DB:compilation-db}
    username: ${POSTGRES_USER:user}
    password: ${POSTGRES_PASSWORD:user}
    driver-class-name: org.postgresql.Driver
    initialization-mode: always
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true

statsService:
  url:
  name: stats-service